export const PAYMENT_GATEWAY = Symbol('PAYMENT_GATEWAY');
export const STORE_PAYMENT_ACCOUNTS_REPOSITORY = Symbol(
  'STORE_PAYMENT_ACCOUNTS_REPOSITORY',
);
export const CONNECT_WEBHOOK_EVENTS_REPOSITORY = Symbol(
  'CONNECT_WEBHOOK_EVENTS_REPOSITORY',
);
