CREATE TYPE "checkout_payment_method" AS ENUM ('cash_on_delivery', 'online');--> statement-breakpoint
CREATE TYPE "checkout_attempt_status" AS ENUM ('creating', 'pending', 'cancelling', 'succeeded', 'expired', 'cancelled', 'failed');--> statement-breakpoint
CREATE TYPE "order_status" AS ENUM ('placed', 'preparing', 'shipped', 'delivered', 'cancelled', 'returned');--> statement-breakpoint
CREATE TYPE "order_payment_status" AS ENUM ('unpaid', 'paid', 'refund_pending', 'refunded', 'refund_failed');--> statement-breakpoint
CREATE TYPE "checkout_reservation_disposition" AS ENUM ('held', 'released', 'consumed', 'returned');--> statement-breakpoint
ALTER TYPE "outbox_event_type" ADD VALUE IF NOT EXISTS 'order.email.intent';--> statement-breakpoint
CREATE TABLE "checkout_quotes" ("id" uuid PRIMARY KEY NOT NULL, "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade, "store_id" uuid NOT NULL REFERENCES "store"("id") ON DELETE restrict, "cart_id" uuid NOT NULL REFERENCES "carts"("id") ON DELETE cascade, "cart_version" integer NOT NULL, "snapshot" jsonb NOT NULL, "snapshot_hash" varchar(64) NOT NULL, "expires_at" timestamp with time zone NOT NULL, "consumed_at" timestamp with time zone, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "checkout_quotes_version_check" CHECK ("cart_version" > 0));--> statement-breakpoint
CREATE TABLE "checkout_attempts" ("id" uuid PRIMARY KEY NOT NULL, "user_id" text REFERENCES "user"("id") ON DELETE set null, "store_id" uuid NOT NULL REFERENCES "store"("id") ON DELETE restrict, "cart_id" uuid REFERENCES "carts"("id") ON DELETE set null, "quote_id" uuid REFERENCES "checkout_quotes"("id") ON DELETE set null, "quote_reference_id" uuid NOT NULL, "payment_method" "checkout_payment_method" NOT NULL, "status" "checkout_attempt_status" NOT NULL, "snapshot" jsonb NOT NULL, "idempotency_key" varchar(128) NOT NULL, "request_hash" varchar(64) NOT NULL, "payment_url" text, "expires_at" timestamp with time zone, "payment_review_required" boolean DEFAULT false NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE "orders" ("id" uuid PRIMARY KEY NOT NULL, "attempt_id" uuid NOT NULL UNIQUE REFERENCES "checkout_attempts"("id") ON DELETE restrict, "store_id" uuid NOT NULL REFERENCES "store"("id") ON DELETE restrict, "user_id" text REFERENCES "user"("id") ON DELETE set null, "status" "order_status" DEFAULT 'placed' NOT NULL, "payment_method" "checkout_payment_method" NOT NULL, "payment_status" "order_payment_status" NOT NULL, "version" integer DEFAULT 1 NOT NULL, "currency" varchar(3) DEFAULT 'usd' NOT NULL, "subtotal" integer NOT NULL, "shipping_fee" integer NOT NULL, "total" integer NOT NULL, "refunded_amount" integer DEFAULT 0 NOT NULL, "account_email" text NOT NULL, "account_phone" text NOT NULL, "shipping_address" jsonb NOT NULL, "shipping_policy" text, "payment_review_required" boolean DEFAULT false NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "orders_amounts_check" CHECK ("subtotal" >= 0 AND "shipping_fee" >= 0 AND "total" = "subtotal" + "shipping_fee" AND "refunded_amount" >= 0));--> statement-breakpoint
CREATE TABLE "order_items" ("id" uuid PRIMARY KEY NOT NULL, "order_id" uuid NOT NULL REFERENCES "orders"("id") ON DELETE restrict, "store_id" uuid NOT NULL, "product_id" uuid NOT NULL, "variant_id" uuid NOT NULL, "name" text NOT NULL, "variant_title" text NOT NULL, "sku" text NOT NULL, "unit_price" integer NOT NULL, "quantity" integer NOT NULL, "line_total" integer NOT NULL, "inventory_policy" "inventory_policy" NOT NULL, CONSTRAINT "order_items_amount_check" CHECK ("quantity" BETWEEN 1 AND 99 AND "unit_price" >= 0 AND "line_total" = "unit_price" * "quantity"), CONSTRAINT "order_items_order_variant_uidx" UNIQUE("order_id", "variant_id"));--> statement-breakpoint
CREATE TABLE "checkout_reservations" ("id" uuid PRIMARY KEY NOT NULL, "attempt_id" uuid NOT NULL REFERENCES "checkout_attempts"("id") ON DELETE restrict, "order_id" uuid REFERENCES "orders"("id") ON DELETE restrict, "store_id" uuid NOT NULL, "variant_id" uuid NOT NULL, "quantity" integer NOT NULL, "inventory_policy" "inventory_policy" NOT NULL, "disposition" "checkout_reservation_disposition" DEFAULT 'held' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "checkout_reservations_quantity_check" CHECK ("quantity" BETWEEN 1 AND 99), CONSTRAINT "checkout_reservations_attempt_variant_uidx" UNIQUE("attempt_id", "variant_id"));--> statement-breakpoint
CREATE TABLE "order_events" ("id" uuid PRIMARY KEY NOT NULL, "order_id" uuid NOT NULL REFERENCES "orders"("id") ON DELETE restrict, "store_id" uuid NOT NULL, "version" integer NOT NULL, "kind" varchar(64) NOT NULL, "actor_user_id" text, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "order_events_order_version_uidx" UNIQUE("order_id", "version"));--> statement-breakpoint
CREATE TABLE "commerce_commands" ("id" uuid PRIMARY KEY NOT NULL, "actor_user_id" text NOT NULL, "operation" varchar(64) NOT NULL, "resource_id" uuid NOT NULL, "idempotency_key" varchar(128) NOT NULL, "request_hash" varchar(64) NOT NULL, "attempt_id" uuid REFERENCES "checkout_attempts"("id") ON DELETE restrict, "order_id" uuid REFERENCES "orders"("id") ON DELETE restrict, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "commerce_commands_actor_operation_resource_key_uidx" UNIQUE("actor_user_id", "operation", "resource_id", "idempotency_key"));--> statement-breakpoint
CREATE INDEX "checkout_quotes_expiry_idx" ON "checkout_quotes" ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "checkout_attempts_quote_uidx" ON "checkout_attempts" ("quote_reference_id");--> statement-breakpoint
CREATE UNIQUE INDEX "checkout_attempts_active_cart_uidx" ON "checkout_attempts" ("cart_id") WHERE "status" IN ('creating', 'pending', 'cancelling');--> statement-breakpoint
CREATE UNIQUE INDEX "checkout_attempts_actor_key_uidx" ON "checkout_attempts" ("user_id", "idempotency_key");--> statement-breakpoint
CREATE INDEX "checkout_attempts_user_created_idx" ON "checkout_attempts" ("user_id", "created_at", "id");--> statement-breakpoint
CREATE INDEX "orders_user_created_idx" ON "orders" ("user_id", "created_at", "id");--> statement-breakpoint
CREATE INDEX "orders_store_status_created_idx" ON "orders" ("store_id", "status", "created_at", "id");--> statement-breakpoint
CREATE INDEX "checkout_reservations_variant_disposition_idx" ON "checkout_reservations" ("variant_id", "disposition");
