export const PLAN_PRICES_REPOSITORY = Symbol('PLAN_PRICES_REPOSITORY');
export const PLATFORM_PLANS_REPOSITORY = Symbol('PLATFORM_PLANS_REPOSITORY');
export const PUBLIC_PLANS_REPOSITORY = Symbol('PUBLIC_PLANS_REPOSITORY');
