export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_ADDRESSES_REPOSITORY = Symbol('USER_ADDRESSES_REPOSITORY');
